# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
  config.vm.box = "centos/7"
  config.vm.synced_folder ".", "/vagrant" , disabled: true
  config.vm.provider "virtualbox" do |v|
    v.memory = 256
    v.cpus = 1
  end

  config.vm.define "hw09" do |hw9|
    hw9.vm.network "private_network", ip: "192.168.100.10", virtualbox__intnet: "net1"
    hw9.vm.hostname = "hw9"
    hw9.vm.provision "shell", path: "vagrant.sh"
  end
end
